[package]
name = "simple_rijndael_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "simple_rijndael_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
simple-rijndael = "0.3.2"
