[package]
name = "simple_rijndael_nif"
version = "0.1.0"
authors = []
edition = "2021"
rust-version = "1.79"
publish = false

[lib]
name = "simple_rijndael_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
simple-rijndael = "0.3.2"
